/** Kenney-style prototype pack catalog (GLB under /game/prototype/glb). */

export const PROTOTYPE_MODELS = [
  'floor-square',
  'floor-small-square',
  'floor-diagonal',
  'floor-small-diagonal',
  'floor-thick',
  'floor-thick-corner-diagonal',
  'floor-thick-corner-round',
  'floor-thick-corner-rounded',
  'wall',
  'wall-low',
  'wall-round',
  'wall-round-low',
  'wall-corner',
  'wall-corner-low',
  'wall-corner-rounded',
  'wall-corner-rounded-low',
  'wall-diagonal',
  'wall-diagonal-low',
  'wall-doorway',
  'wall-doorway-garage',
  'wall-doorway-round',
  'wall-doorway-sliding',
  'wall-doorway-wide',
  'wall-doorway-wide-sliding',
  'wall-window-small',
  'wall-window-medium',
  'wall-window-large',
  'wall-window-barred-small',
  'wall-window-barred-medium',
  'wall-window-barred-large',
  'wall-window-cutout-small',
  'wall-window-cutout-medium',
  'wall-window-cutout-large',
  'stairs',
  'stairs-narrow',
  'stairs-small',
  'stairs-small-narrow',
  'stairs-diagonal',
  'stairs-diagonal-narrow',
  'stairs-diagonal-small',
  'stairs-diagonal-small-narrow',
  'column',
  'column-low',
  'column-rounded',
  'column-rounded-low',
  'column-triangle',
  'column-triangle-low',
  'crate',
  'crate-color',
  'pipe',
  'pipe-section',
  'pipe-corner',
  'pipe-half',
  'pipe-half-section',
  'pipe-split',
  'button-floor-round',
  'button-floor-round-small',
  'button-floor-square',
  'button-floor-square-small',
  'lever-single',
  'lever-double',
  'coin',
  'flag',
  'ladder',
  'ladder-color',
  'ladder-top',
  'target-a-round',
  'target-a-square',
  'target-b-round',
  'target-b-square',
  'door-garage',
  'door-rotate',
  'door-sliding',
  'door-sliding-double',
  'door-sliding-double-round',
  'door-sliding-double-wide',
  'shape-cube',
  'shape-cube-half',
  'shape-cube-rounded',
  'shape-cylinder',
  'shape-cylinder-detailed',
  'shape-cylinder-half',
  'shape-cylinder-half-detailed',
  'shape-hexagon',
  'shape-hexagon-half',
  'shape-hollow-cylinder',
  'shape-hollow-cylinder-detailed',
  'shape-hollow-cylinder-half',
  'shape-hollow-cylinder-half-detailed',
  'shape-hollow-hexagon',
  'shape-hollow-hexagon-half',
  'shape-slope',
  'shape-triangular-prism',
  'shape-triangular-prism-low',
  'indicator-round-a',
  'indicator-round-b',
  'indicator-round-c',
  'indicator-special-arrow',
  'indicator-special-cross',
  'indicator-special-area',
  'indicator-doorway',
  'figurine',
  'figurine-large',
  'figurine-cube',
  'figurine-cube-detailed',
  'weapon-sword',
  'weapon-shield',
] as const;

export type PrototypeModelId = (typeof PROTOTYPE_MODELS)[number];

export function modelUrl(name: string): string {
  return `/game/prototype/glb/${name}.glb`;
}

export function previewUrl(name: string): string {
  return `/game/prototype/previews/${name}.png`;
}

export function textureUrl(variation: 'a' | 'b' | 'c' = 'a'): string {
  return `/game/prototype/textures/variation-${variation}.png`;
}
