/** Kenney-style prototype pack catalog (GLB under /game/prototype/glb). */

export const PROTOTYPE_MODELS = [
  'floor-square',
  'floor-small-square',
  'floor-diagonal',
  'floor-small-diagonal',
  'floor-thick',
  'floor-thick-corner-diagonal',
  'floor-thick-corner-round',
  'floor-thick-corner-rounded',
  'wall',
  'wall-low',
  'wall-round',
  'wall-round-low',
  'wall-corner',
  'wall-corner-low',
  'wall-corner-rounded',
  'wall-corner-rounded-low',
  'wall-diagonal',
  'wall-diagonal-low',
  'wall-doorway',
  'wall-doorway-garage',
  'wall-doorway-round',
  'wall-doorway-sliding',
  'wall-doorway-wide',
  'wall-doorway-wide-sliding',
  'wall-window-small',
  'wall-window-medium',
  'wall-window-large',
  'wall-window-barred-small',
  'wall-window-barred-medium',
  'wall-window-barred-large',
  'wall-window-cutout-small',
  'wall-window-cutout-medium',
  'wall-window-cutout-large',
  'stairs',
  'stairs-narrow',
  'stairs-small',
  'stairs-small-narrow',
  'stairs-diagonal',
  'stairs-diagonal-narrow',
  'stairs-diagonal-small',
  'stairs-diagonal-small-narrow',
  'column',
  'column-low',
  'column-rounded',
  'column-rounded-low',
  'column-triangle',
  'column-triangle-low',
  'crate',
  'crate-color',
  'pipe',
  'pipe-section',
  'pipe-corner',
  'pipe-half',
  'pipe-half-section',
  'pipe-split',
  'button-floor-round',
  'button-floor-round-small',
  'button-floor-square',
  'button-floor-square-small',
  'lever-single',
  'lever-double',
  'coin',
  'flag',
  'ladder',
  'ladder-color',
  'ladder-top',
  'target-a-round',
  'target-a-square',
  'target-b-round',
  'target-b-square',
  'door-garage',
  'door-rotate',
  'door-sliding',
  'door-sliding-double',
  'door-sliding-double-round',
  'door-sliding-double-wide',
  'shape-cube',
  'shape-cube-half',
  'shape-cube-rounded',
  'shape-cylinder',
  'shape-cylinder-detailed',
  'shape-cylinder-half',
  'shape-cylinder-half-detailed',
  'shape-hexagon',
  'shape-hexagon-half',
  'shape-hollow-cylinder',
  'shape-hollow-cylinder-detailed',
  'shape-hollow-cylinder-half',
  'shape-hollow-cylinder-half-detailed',
  'shape-hollow-hexagon',
  'shape-hollow-hexagon-half',
  'shape-slope',
  'shape-triangular-prism',
  'shape-triangular-prism-low',
  'indicator-round-a',
  'indicator-round-b',
  'indicator-round-c',
  'indicator-special-arrow',
  'indicator-special-cross',
  'indicator-special-area',
  'indicator-doorway',
  'figurine',
  'figurine-large',
  'figurine-cube',
  'figurine-cube-detailed',
  'weapon-sword',
  'weapon-shield',
] as const;

export type PrototypeModelId = (typeof PROTOTYPE_MODELS)[number];

export function modelUrl(name: string): string {
  return `/game/prototype/glb/${name}.glb`;
}

export function previewUrl(name: string): string {
  return `/game/prototype/previews/${name}.png`;
}

export function textureUrl(variation: 'a' | 'b' | 'c' = 'a'): string {
  return `/game/prototype/textures/variation-${variation}.png`;
}

/**
 * Approximate local-space AABB size [x, y, z] for prototype GLBs.
 * Used when a live mesh hasn't been measured yet — keeps collision close to visuals.
 * Units match Kenney prototype pack (≈1 unit tiles).
 */
export const MODEL_FOOTPRINTS: Record<string, [number, number, number]> = {
  'floor-square': [2, 0.2, 2],
  'floor-small-square': [1, 0.2, 1],
  'floor-diagonal': [2, 0.2, 2],
  'floor-small-diagonal': [1, 0.2, 1],
  'floor-thick': [2, 0.5, 2],
  'floor-thick-corner-diagonal': [2, 0.5, 2],
  'floor-thick-corner-round': [2, 0.5, 2],
  'floor-thick-corner-rounded': [2, 0.5, 2],
  wall: [2, 2, 0.25],
  'wall-low': [2, 1, 0.25],
  'wall-round': [2, 2, 0.25],
  'wall-round-low': [2, 1, 0.25],
  'wall-corner': [2, 2, 2],
  'wall-corner-low': [2, 1, 2],
  'wall-diagonal': [2.2, 2, 0.3],
  'wall-diagonal-low': [2.2, 1, 0.3],
  'wall-doorway': [2, 2, 0.25],
  'wall-doorway-garage': [2.5, 2.2, 0.3],
  'wall-doorway-sliding': [2, 2, 0.25],
  'wall-doorway-wide': [3, 2, 0.25],
  stairs: [2, 1.2, 2],
  'stairs-narrow': [1, 1.2, 2],
  'stairs-small': [1.2, 0.7, 1.2],
  'stairs-small-narrow': [0.8, 0.7, 1.2],
  'stairs-diagonal': [2.2, 1.2, 2.2],
  'stairs-diagonal-narrow': [1.2, 1.2, 2.2],
  column: [0.6, 2, 0.6],
  'column-low': [0.6, 1, 0.6],
  'column-rounded': [0.6, 2, 0.6],
  crate: [1, 1, 1],
  'crate-color': [1, 1, 1],
  'door-garage': [2.2, 2.2, 0.35],
  'door-rotate': [1.2, 2.1, 0.15],
  'door-sliding': [1.2, 2.1, 0.15],
  'door-sliding-double': [2.2, 2.1, 0.15],
  'door-sliding-double-round': [2.2, 2.1, 0.15],
  'door-sliding-double-wide': [3.2, 2.1, 0.15],
  'shape-cylinder': [1.2, 0.35, 1.2],
  'shape-hexagon': [1.4, 0.25, 1.4],
  'target-a-square': [1, 1, 0.2],
  'target-a-round': [1, 1, 0.2],
};

export function modelFootprint(model?: string | null): [number, number, number] | null {
  if (!model) return null;
  return MODEL_FOOTPRINTS[model] ?? null;
}

/** Default door GLB when placing a Door entity without picking a brush model. */
export const DEFAULT_DOOR_MODEL = 'door-sliding';

