/**
 * Shared tuning values for the authoritative simulation.
 * Physics/movement numbers live in `shared/sim-constants.ts` (also used by Play Test).
 */

export {
  TICK_RATE_HZ,
  TICK_DT_MS,
  PLAYER_RADIUS,
  PLAYER_HEIGHT,
  MAX_GROUND_SPEED,
  SPRINT_MULTIPLIER,
  GROUND_ACCEL,
  GROUND_FRICTION,
  AIR_ACCEL,
  AIR_CONTROL,
  MAX_AIR_SPEED_MULT,
  CROUCH_SPEED_MULTIPLIER,
  GRAVITY,
  APEX_GRAVITY_MULT,
  APEX_VZ_THRESHOLD,
  JUMP_VELOCITY,
  DOUBLE_JUMP_MOD,
  DOUBLE_JUMP_VELOCITY,
  JUMP_CUT_MULTIPLIER,
  COYOTE_TIME_MS,
  JUMP_BUFFER_MS,
  MAX_FALL_SPEED,
  LAND_SNAP_SLOW,
  LAND_SNAP_FAST,
  GROUND_FOLLOW_SPEED,
  LAND_STEP_CLIMB,
  LAND_STEP_DESCEND,
  LEDGE_ASSIST,
  COLLISION_SKIN,
  VOID_Z,
  WALL_JUMP_ENABLED_DEFAULT,
  WALL_JUMP_HORIZ_VEL,
  WALL_JUMP_VERT_VEL,
  WALL_SLIDE_GRAV_MULT,
  WALL_JUMP_LOCKOUT_MS,
  WALL_JUMP_SAME_WALL_COOLDOWN_MS,
  MAX_ENERGY,
  ENERGY_DRAIN_RATE,
  ENERGY_REGEN_RATE,
  ENERGY_EXHAUSTED_THRESHOLD,
  ENERGY_EXHAUSTED_SPEED_MULT,
  JUMP_ENERGY_COST,
  SLIDE_ENERGY_COST,
  FLIP_ENERGY_COST,
  FLIP_DURATION_MS,
  FLIP_COOLDOWN_MS,
  FLIP_VELOCITY,
  FLIP_PUSH_SPEED,
  JUMP_PAD_BOOST,
  HITSCAN_RANGE,
  HITSCAN_DAMAGE,
  SHOOT_COOLDOWN_MS,
  MELEE_MOVE_MULT,
  MELEE_DURATION_MS,
} from '../../../shared/sim-constants.js';

export const MIN_PLAYERS_TO_START = 1;
export const HORDE_MIN_PLAYERS_TO_START = 4;
export const COMPETITIVE_MIN_PLAYERS_TO_START = 2;
export const LOBBY_COUNTDOWN_MS = 5000;
export const MATCH_DURATION_MS = 180_000;

export const WORLD_WIDTH = 48;
export const WORLD_HEIGHT = 10;
export const FINISH_X = WORLD_WIDTH - 2;
export const SPAWN_X = 2;
export const SPAWN_Z = 0;

import { MAX_GROUND_SPEED } from '../../../shared/sim-constants.js';
export const RUNNER_MOVE_SPEED = MAX_GROUND_SPEED;
export const TRAPPER_MOVE_SPEED = MAX_GROUND_SPEED * 0.92;

export const OBSTACLE_DAMAGE = 40;
export const OBSTACLE_HIT_COOLDOWN_MS = 600;
